name: WebExtension Lint, Build, Test, Deploy

on:
    push:
        branches:
            - master
            - dev
    pull_request:
        types:
            - opened
            - synchronize
            - reopened
            - labeled
    workflow_dispatch:
        inputs:
            deploy:
                description: "Deploy location"
                required: true
                default: "none"
                type: choice
                options:
                    - production
                    - staging
                    - none

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    ci:
        name: WebExtension Lint, Build, Test, Deploy
        runs-on: aws-runner
        env:
            DEPLOY_PROD: ${{ (github.event_name == 'workflow_dispatch' && github.event.inputs.deploy == 'production') || (github.event_name == 'push' && github.ref_type == 'branch' && github.ref_name == 'master') }}
            DEPLOY_STAGE: ${{ (github.event_name == 'workflow_dispatch' && github.event.inputs.deploy == 'staging') || (github.event_name == 'push' && github.ref_type == 'branch' && github.ref_name == 'dev') || (github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'staged')) }}
        concurrency:
            group: ${{ github.workflow }}-ci-${{ github.ref }}
            cancel-in-progress: true

        steps:
            - name: Set up Go
              uses: actions/setup-go@v3
              with:
                  go-version: 1.18.3

            - uses: actions/setup-node@v3
              with:
                  node-version: "18"

            - name: Install Yarn
              run: npm install -g yarn

            - name: Checkout code
              uses: actions/checkout@v3
              with:
                  submodules: recursive

            - id: cache-paths
              run: |
                  echo "::set-output name=go-build::$(go env GOCACHE)"
                  echo "::set-output name=go-mod::$(go env GOMODCACHE)"

            - name: Go Build Cache
              uses: actions/cache@v3
              with:
                  path: ${{ steps.cache-paths.outputs.go-build }}
                  key: ${{ runner.os }}-go-build-${{ hashFiles('go.sum') }}

            - name: Go Mod Cache
              uses: actions/cache@v3
              with:
                  path: ${{ steps.cache-paths.outputs.go-mod }}
                  key: ${{ runner.os }}-go-mod-${{ hashFiles('go.sum') }}

            - name: Node Modules Cache
              uses: actions/cache@v3
              with:
                  path: node_modules
                  key: ${{ runner.os }}-node_modules-${{ hashFiles('yarn.lock') }}

            - name: Install Dependencies
              run: |
                  npm config set "@fortawesome:registry" https://npm.fontawesome.com/
                  npm config set '//npm.fontawesome.com/:_authToken' "${{ secrets.FONTAWESOME_TOKEN }}"
                  make deps dev_deps

            - name: Run Linter
              run: make lint

            - name: Build App
              run: make ${{ (env.DEPLOY_PROD == 'true' && 'prod') || 'stage' }}
